### ISSUE TITLE
@username => @Username

### ISSUE THREAD

**Issue by MrMooky** [XetaIO/Xetaravel-Mentions#11]
For some strange reason `@username` gets changed to `@Username` (uppercase), even though the username is `@username`.

**Comment by Xety** [comment]
Yes it's because of the `Str::title` from Laravel used here : https://github.com/XetaIO/Xetaravel-Mentions/blob/master/src/Parser/MentionParser.php#L88 and in Laravel : https://github.com/laravel/framework/blob/5.6/src/Illuminate/Support/Str.php#L394 . If you want to delete this fonction, do a custom parser as explained in the readme and overwrite the `replace` method.
